version: '3.7'
services:
  nope-db:
    image: mysql:latest
    container_name: nope-mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
